version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: dev-nginx
    volumes:
      - ./apps/server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/server/nginx/wait-for-it.sh:/wait-for-it.sh
      - ./apps/server/nginx/docker-entrypoint.production.sh:/docker-entrypoint.production.sh
    command: /bin/bash -c "chmod +x /docker-entrypoint.production.sh && /docker-entrypoint.production.sh"
    ports:
      - "80:80"
    depends_on:
      - dev-server
    links:
      - dev-server
    networks:
      - dev-dothis-network
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    env_file:
      - apps/server/development.env
    ports:
      - "8080"
    restart: always
    networks:
      - dev-dothis-network
  db-mysql:
    platform: linux/arm64/v8
    container_name: dothis-mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}
      - TZ=Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./apps/server/db/data/mysql:/var/lib/mysql
      - ./apps/server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - dev-dothis-network
  cache-redis:
    platform: linux/arm64/v8
    container_name: dothis-redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./apps/server/db/redis/data:/data
      - ./apps/server/db/redis/conf/redis.conf:/usr/local/conf/redis.conf
    ports:
      - 6379:6379
    networks:
      - dev-dothis-network

networks:
  dev-dothis-network:

