name: CI-CD

on:
  pull_request:
    branches: [deploy]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: build

  build:
    name: Build, Deploy to S3 Bucket
    runs-on: ubuntu-latest

    env:
      working-directory: ./

    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: zip file
        working-directory: ./
        run: zip -r dothisBackEnd.zip ./ -x "apps/dashboard-web" -x "apps/request-web" -x "packages/share" -x "packages/ui"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        working-directory: ./
        run: aws s3 cp --region ap-northeast-2 ./dothisBackEnd.zip ${{ secrets.AWS_S3_BUCKET_NAME }}

      - name: deploy with AWS codeDeploy
        working-directory: ./apps/api
        run: aws deploy create-deployment
          --application-name github-action
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name github-action-group
          --s3-location bucket=dothis,bundleType=zip,key=git-archive/dothisBackEnd.zip

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0
