name: CI-CD

on:
  pull_request:
    branches: [ deploy ]

jobs:
  build:
    name: Build, Deploy to S3 Bucket
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./apps/back-end

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Npm Setup & Build
        run : | 
         cd ./apps/back-end && npm install
          
     # - name: Create Deploy Folder
      #  run : |
       #   mkdir out
        #  cp appspec.yml out
        #  cp start-update.sh out
        #  cp .env.production out
        #  cp -r .next out
        #  cp -r public out
        #  cp package.json out
        #  cp next.config.mjs out
          
      - name: archive dothis 
        run: tar cvfz ./dothis.tar.gz out
        working-directory: ${{ env.working-directory }}
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./dothis.tar.gz ${{ secrets.AWS_S3_BUCKET_NAME }}
        working-directory: ${{ env.working-directory }}
        
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name github-action
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name github-action-group
          --s3-location bucket=dothis,bundleType=tgz,key=git-archive/dothis.tar.gz
