# This is a basic workflow to help you get started with Actions

name: dashboard-page CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ['lending/deploy']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: build
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code.
        uses: actions/checkout@master
        with:
          ref: main

      - name: Install pnpm
        run: |
          npm install -g pnpm

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: |
          pnpm install -no-frozen-lockfile

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.16.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      #      - name: make dotenv
      #        run: |
      #          touch .env.production
      #          echo NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} >> .env.production

      - name: Generate Environment Variables File for Production
        working-directory: ./apps/dashboard-web
        run: |
          pwd
          touch .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          cat .env

      - name: build dashboard
        run: |
          pnpm build:dashboard

      - name: Deploy Next.js app
        run: |
          cd apps/dashboard-web && pnpm sst deploy --stage prod
